kafka:
  bootstrapServers: "localhost:29092"
  acksRequiredOnWrite: 1
  retries: 10
  schemaRegistryUrl: "http://localhost:8090"
  streamsApplicationId: "energy_app"
  deviceDataTopic: "device-data"

database:
  driverClass: com.mysql.cj.jdbc.Driver
  user: root
  password: secret-pw
  url: "jdbc:mysql://0.0.0.0:3306/energy_data"
  properties:
    charSet: UTF-8
  maxWaitForConnection: 1s
  validationQuery: "/* MyService Health Check */ SELECT 1"
  validationQueryTimeout: 3s
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute

